#! /bin/bash

sudo dpkg --add-architecture i386
sudo apt update
sudo apt install -y\
	zip \
	xcompmgr \
	x11-utils \
	uuid-dev \
	subversion \
	snapcraft \
	ruby \
	rpm \
	python-yaml \
	python-setuptools \
	python-psutil \
	python-openssl \
	python-crypto \
	python2-dev \
	php7.4-cgi \
	p7zip \
	openbox \
	mesa-common-dev \
	libxtst-dev \
	libxtst6 \
	libxt-dev \
	libxss-dev \
	libxslt1-dev \
	libxshmfence-dev \
	libxrender1 \
	libxrandr2 \
	libxkbcommon-dev \
	libxinerama1 \
	libxi6 \
	libxfixes3 \
	libxdamage1 \
	libxcursor1 \
	libxcomposite1 \
	libx11-xcb1 \
	libwww-perl \
	libwayland-egl1-mesa \
	libvulkan-dev \
	libvulkan1 \
	libva-dev \
	libudev-dev \
	libssl-dev \
	libsqlite3-dev \
	libspeechd-dev \
	libspeechd2 \
	libsctp-dev \
	libpulse-dev \
	libpulse0 \
	libpixman-1-0 \
	libpci-dev \
	libpango-1.0-0 \
	libnss3-dev \
	libnspr4-dev \
	libkrb5-dev \
	libjpeg-dev \
	libinput-dev \
	libinput10 \
	libgtk-3-dev \
	libgtk-3-0 \
	libglu1-mesa-dev \
	libgbm-dev \
	libgbm1 \
	libfontconfig1 \
	libffi-dev \
	libevdev-dev \
	libelf-dev \
	libdrm-dev \
	libcurl4-gnutls-dev \
	libcups2-dev \
	libcups2 \
	libcap-dev \
	libcairo2-dev \
	libcairo2 \
	libc6-i386 \
	libbz2-dev \
	libbrlapi-dev \
	libbrlapi0.7 \
	libbluetooth-dev \
	libatspi2.0-dev \
	libatspi2.0-0 \
	libatk1.0-0 \
	libasound2-dev \
	libappindicator3-dev \
	libappindicator3-1 \
	libapache2-mod-php7.4 \
	lib32stdc++6 \
	lib32gcc-s1 \
	gperf \
	elfutils \
	devscripts \
	cdbs \
	binutils-mipsel-linux-gnu \
	binutils-mips64el-linux-gnuabi64 \
	binutils-arm-linux-gnueabihf \
	binutils-aarch64-linux-gnu \
	apache2-bin \
	linux-libc-dev:i386 \
	libx11-xcb1:i386 \
	libpci3:i386 \
	lib32z1 \
	lighttpd \
	xvfb \
	x11-utils \
	libncurses5:i386 \
	libstdc++6:i386 \
	zlib1g:i386 \
	python-yaml \
	python-setuptools \
	python-psutil \
	python-openssl \
	libxt-dev \
	libbz2-dev \
	libbrlapi-dev \
	libbluetooth-dev \
	lib32stdc++6 \
	lib32gcc1 \
	gperf \
	python

